spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user_user
    password: user_pass
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: dev