spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/catalog_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: catalog_user
    password: catalog_pass
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: dev  # ✅ 使用 dev